### ISSUE TITLE
Bug? Memory Error.

### ISSUE THREAD

**Issue by JonMcPhalen** [parallaxinc/Propeller-Tool#121] opened 2021-02-18 23:52 UTC
I noticed that the main menu was grayed out but still operated. At the bottom of the screen, it appears that items that should have been written to a menu are written to the info/status line.
![pt_2 5 0__error](https://user-images.githubusercontent.com/4042568/108436984-413d4400-7201-11eb-8e2d-c8b13e85249d.png)

**Comment by PropGit** [comment] 2021-02-19 22:55
Yes, this is definitely a bug.  I've been chasing that darned thing since v1.2.x?  Didn't ever find what was causing it until recently (I think).  Seems to happen at random times but sometimes is reproducible.  Thought I had it fixed just before v2.5.0, but I've since seen it occur again.

I started a issue #80 for it.

I think there's a component that's injecting itself into the app's windows message chain, intercepting messages to handle a custom message, but mistakenly passing some messages to the wrong control (in this case, the status bar); causing the wrong control to perform the task.  Crazy situation, but now I stand a better chance of finding it and fixing it.  It's either a technique that is written incorrectly, or I've contained a control manually and given it the wrong owner ID, so the messages don't hit the intended target.

Now that **this** issue references that one (#80), I'll close this issue.

**Closed by PropGit** 2021-02-19 22:55 UTC
