### ISSUE TITLE
Inconsistent P1 EEPROM verification problem "Stalled communication"

### ISSUE THREAD

**Issue by wadecsheldon** [parallaxinc/Propeller-Tool#124] opened 2021-02-25 21:59 UTC
I ran into a strange issue while working on some P1 code using Propeller Tool v2.5.1 today, it seems to have magically resolved itself for now but I thought it was still worth a report

I have an object I wrote to interface to an ADC which is referenced in several test programs, all of which are compiling and running fine, but after making a change to some of the ADC functions I kept getting an error saying communication was stalled due to a system issue while verifying EEPROM. The actual uploads seemed to work fine and RAM verified correctly. The issue was only affecting programs that referenced the ADC object, but not the ADC object itself if I uploaded it directly, and it persisted across a reboot and across multiple devices and USB ports.

The issue finally went away after commenting out the changes to the ADC object, and now it's not happening after uncommenting them again. The issue only started happening a while after making the changes to the ADC object as well, uploading some test programs immediately afterwards to make sure I hadn't broken an older function worked fine.

Hopefully it stays away for now, but it really has me stumped

**Comment by PropGit** [comment] 2021-02-25 22:24
Thanks @wadecsheldon.  I added that error message for a case that should be serious, but wasn't sure if it'd ever happen.  I've seen it myself a couple times, but noticed all seemed to be well and future downloads worked perfectly afterwards too.

I'll try to duplicate.  If you have an example project that seems to cause it (your current one or another) that you can share an archive of, it may help; however, I really think it has to do with timing... in particular, with a large app download vs. a short one.  Or perhaps it has to do with how busy (or not) the computer is at the time of the download.

**Comment by PropGit** [comment] 2021-02-25 23:33
Understood.

With all that considered, my theory sounds completely wrong.  This may be a difficult one to solve.

If you have it happen with evidence that the application didn't completely download (failed to run for no other apparent reason), please report it here.  (I've yet to see it be an actual fatal download attempt).  In the meantime, I'll update this issue as I have more details.

**Comment by PropGit** [comment] 2021-03-05 16:41
**Update:**

Another customer and another business associate have reported this also and their efforts led me to find the cause.  All indications are that it's a bogus error and that (most or all of the time) the P1 has actually been programmed properly, but the software failed to get confirmation and relay that to the user.

It also happens, and is repeatable, by simply doing an identify and leaving the result dialog open for > 5 seconds.

This has to do with a safety-timeout built into the serial handing routines that uses a once-valid timeout period which is now invalid for the new techniques employed by the Propeller Tool.  Essentially, it is giving up before the P1 has had a chance to properly respond, and then it misses/ignores the response after that moment.  The identify-dialog case happens because the operation was successful (quickly), but the UI prevented the code which releases the timeout state from executing until after the user response.

There is a possibility that the error message is valid, of course, but it seems that the most common case is proper download but errant response to the user.

This will be fixed in v2.5.2 to be release soon.

**Comment by PropGit** [comment] 2021-03-06 15:27
Fixed in v2.5.2.

**Closed by PropGit** 2021-03-06 15:27 UTC
Labels: bug
